// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {instance} from '../models';
import {editor} from '../models';
import {config} from '../models';

export function CheckProjectStatus(arg1:string):Promise<boolean>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function FetchInstances():Promise<Array<instance.Instance>>;

export function FetchLocalProjects():Promise<Array<editor.Project>>;

export function GetConfig():Promise<config.Config>;

export function GetContentFromURL(arg1:string):Promise<instance.Content>;

export function GetContentSiteURL(arg1:string,arg2:string):Promise<string>;

export function GetContentVersionURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetContentVersionsURL(arg1:string,arg2:string):Promise<string>;

export function GetInstances():Promise<Array<instance.Instance>>;

export function GetProjectHistory(arg1:string):Promise<editor.GitHistory>;

export function LoadProjectMeta(arg1:string):Promise<instance.Meta>;

export function ReleaseProject(arg1:string,arg2:string):Promise<void>;

export function Run(arg1:instance.Release):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveProjectMeta(arg1:string,arg2:instance.Meta):Promise<void>;

export function SelectLogoFile():Promise<string>;

export function StartMicrosoftLogin():Promise<void>;

export function SyncProject(arg1:string,arg2:string):Promise<void>;
