// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchInstances() {
  return window['go']['main']['App']['FetchInstances']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
