// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProjectStatus(arg1) {
  return window['go']['main']['App']['CheckProjectStatus'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function FetchInstances() {
  return window['go']['main']['App']['FetchInstances']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetContentFromURL(arg1) {
  return window['go']['main']['App']['GetContentFromURL'](arg1);
}

export function GetContentSiteURL(arg1, arg2) {
  return window['go']['main']['App']['GetContentSiteURL'](arg1, arg2);
}

export function GetContentVersionURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetContentVersionURL'](arg1, arg2, arg3);
}

export function GetContentVersionsURL(arg1, arg2) {
  return window['go']['main']['App']['GetContentVersionsURL'](arg1, arg2);
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}

export function GetLocalInstances() {
  return window['go']['main']['App']['GetLocalInstances']();
}

export function GetProjectHistory(arg1) {
  return window['go']['main']['App']['GetProjectHistory'](arg1);
}

export function LoadProjectMeta(arg1) {
  return window['go']['main']['App']['LoadProjectMeta'](arg1);
}

export function ReleaseProject(arg1, arg2) {
  return window['go']['main']['App']['ReleaseProject'](arg1, arg2);
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveProjectMeta(arg1, arg2) {
  return window['go']['main']['App']['SaveProjectMeta'](arg1, arg2);
}

export function SelectLogoFile() {
  return window['go']['main']['App']['SelectLogoFile']();
}

export function StartMicrosoftLogin() {
  return window['go']['main']['App']['StartMicrosoftLogin']();
}

export function SyncProject(arg1, arg2) {
  return window['go']['main']['App']['SyncProject'](arg1, arg2);
}
