// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {github} from '../models';
import {config} from '../models';

export function FetchInstances():Promise<Array<github.Instance>>;

export function GetConfig():Promise<config.Config>;

export function GetInstances():Promise<Array<github.Instance>>;

export function SaveConfig(arg1:config.Config):Promise<void>;
