// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchInstances() {
  return window['go']['main']['App']['FetchInstances']();
}

export function GetInstances() {
  return window['go']['main']['App']['GetInstances']();
}
